import type { Metadata } from "next";
import { Nunito } from "next/font/google"
import "./globals.css";
import Provider from "./provider/Provider";
import { Session } from "next-auth";


const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-nunito"
})
export const metadata: Metadata = {
  title: "NomNomic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode;
  session: Session | null
}>) {
  return (
    <html lang="en" className={`overflow-x-hidden `}>
      <Provider session={session}>

        <body
          className={`antialiased ${nunito.variable} font-nunito`}
        >
          <div className="w-full h-screen">
            {children}
          </div>
        </body>
      </Provider>
    </html>
  );
}
